//! \file Values.cpp
//! \author Henrick Deschamps
//! \version 1.0.0
//! \date December 2019
//! \brief RROSACE values for seaplanes

#include <Values.h>

Values::Values()
    : status_creators_tuples_array{
          {{mode_status, Updater::create<ModeUpdater, 1>,
            Retriever::create<ModeRetriever, 1>},
           {delta_e_status, Updater::create<ElevatorDeflectionUpdater, 1>,
            Retriever::create<ElevatorDeflectionRetriever, 1>},
           {delta_e_c_partial_1_status,
            Updater::create<ElevatorDeflectionCommandPartialUpdater, 1>,
            Retriever::create<ElevatorDeflectionCommandPartialRetriever, 1>},
           {delta_e_c_partial_2_status,
            Updater::create<ElevatorDeflectionCommandPartialUpdater, 2>,
            Retriever::create<ElevatorDeflectionCommandPartialRetriever, 2>},
           {delta_th_c_partial_1_status,
            Updater::create<ThrottleCommandPartialUpdater, 1>,
            Retriever::create<ThrottleCommandPartialRetriever, 1>},
           {delta_th_c_partial_2_status,
            Updater::create<ThrottleCommandPartialUpdater, 2>,
            Retriever::create<ThrottleCommandPartialRetriever, 2>},
           {relay_delta_e_c_1_status,
            Updater::create<RelayElevatorDeflectionCommandPartialUpdater, 1>,
            Retriever::create<RelayElevatorDeflectionCommandPartialRetriever,
                              1>},
           {relay_delta_e_c_2_status,
            Updater::create<RelayElevatorDeflectionCommandPartialUpdater, 2>,
            Retriever::create<RelayElevatorDeflectionCommandPartialRetriever,
                              2>},
           {relay_delta_th_c_1_status,
            Updater::create<RelayThrottleCommandPartialUpdater, 1>,
            Retriever::create<RelayThrottleCommandPartialRetriever, 1>},
           {relay_delta_th_c_2_status,
            Updater::create<RelayThrottleCommandPartialUpdater, 2>,
            Retriever::create<RelayThrottleCommandPartialRetriever, 2>},
           {delta_e_c_status,
            Updater::create<ElevatorDeflectionCommandUpdater, 1>,
            Retriever::create<ElevatorDeflectionCommandRetriever, 1>},
           {delta_th_c_status, Updater::create<ThrottleCommandUpdater, 1>,
            Retriever::create<ThrottleCommandRetriever, 1>},
           {t_status, Updater::create<ThrustUpdater, 1>,
            Retriever::create<ThrustRetriever, 1>},
           {h_status, Updater::create<AltitudeUpdater, 1>,
            Retriever::create<AltitudeRetriever, 1>},
           {vz_status, Updater::create<VerticalSpeedUpdater, 1>,
            Retriever::create<VerticalSpeedRetriever, 1>},
           {va_status, Updater::create<VerticalAccelerationUpdater, 1>,
            Retriever::create<VerticalAccelerationRetriever, 1>},
           {q_status, Updater::create<PitchRateUpdater, 1>,
            Retriever::create<PitchRateRetriever, 1>},
           {az_status, Updater::create<VerticalAccelerationUpdater, 1>,
            Retriever::create<VerticalAccelerationRetriever, 1>},
           {h_f_status, Updater::create<FilteredAltitudeUpdater, 1>,
            Retriever::create<FilteredAltitudeRetriever, 1>},
           {vz_f_status, Updater::create<FilteredVerticalSpeedUpdater, 1>,
            Retriever::create<FilteredVerticalSpeedRetriever, 1>},
           {va_f_status, Updater::create<FilteredTrueAirspeedUpdater, 1>,
            Retriever::create<FilteredTrueAirspeedRetriever, 1>},
           {q_f_status, Updater::create<FilteredPitchRateUpdater, 1>,
            Retriever::create<FilteredPitchRateRetriever, 1>},
           {az_f_status, Updater::create<FilteredVerticalAccelerationUpdater, 1>,
            Retriever::create<FilteredVerticalAccelerationRetriever, 1>},
           {h_c_status, Updater::create<AltitudeRefUpdater, 1>,
            Retriever::create<AltitudeRefRetriever, 1>},
           {vz_c_status, Updater::create<VerticalSpeedRefUpdater, 1>,
            Retriever::create<VerticalSpeedRefRetriever, 1>},
           {va_c_status, Updater::create<TrueAirspeedRefUpdater, 1>,
            Retriever::create<TrueAirspeedRefRetriever, 1>}}} {}
